modLoader = "javafml"
loaderVersion = "[34,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "holographic_health_indicators"
version = "${version}"
displayName = "Holographic Health Indicators"
authors = "ray"
description = '''
Add client-sided, highly customizable, health indicators for entities.
'''
logoFile = "assets/holographic_health_indicators/icon.png"


[[dependencies.holographic_health_indicators]]
modId = "forge"
mandatory = true
versionRange = "[34,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.holographic_health_indicators]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.holographic_health_indicators]]
modId = "cloth_config"
type = "required"
versionRange = "[11.1.118,)"
ordering = "NONE"
side = "CLIENT"
mandatory = true
[[dependencies.holographic_health_indicators]]
modId = "hologram_api"
type = "required"
versionRange = "[1.1.0,)"
ordering = "NONE"
side = "CLIENT"
mandatory = true
