architectury {
    common rootProject.enabled_platforms.split(',')
}

dependencies {
    modApi files("C:\\Users\\Ray\\Documents\\ModDevNew\\HoloAPI\\hologram_api-fabric-1.1.0 1.20.1.jar")
    modApi "me.shedaniel.cloth:cloth-config-fabric:13.0.138"
    modImplementation "net.fabricmc:fabric-loader:$rootProject.fabric_loader_version"
}
