modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "holographic_health_indicators"
version = "${version}"
displayName = "Holographic Health Indicators"
authors = "Me!"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
#logoFile = ""

[[dependencies.holographic_health_indicators]]
modId = "neoforge"
type = "required"
versionRange = "[20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.holographic_health_indicators]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.4,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "holographic_health_indicators.mixins.json"
