modLoader = "javafml"
loaderVersion = "[34,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "holographic_health_indicators"
version = "${version}"
displayName = "Better Damage Indicator"
authors = "ray"
description = '''
Add client-sided, customizable and animated damage indicators when entities take damage/heal.
'''
logoFile = "assets/holographic_health_indicators/icon.png"

[[dependencies.holographic_health_indicators]]
modId = "neoforge"
type = "required"
versionRange = "[20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.holographic_health_indicators]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.4,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.better_damage_indicator]]
modId = "cloth_config"
type = "required"
versionRange = "[11.1.118,)"
ordering = "NONE"
side = "CLIENT"
mandatory = true
[[dependencies.better_damage_indicator]]
modId = "hologram_api"
type = "required"
versionRange = "[1.0.0,)"
ordering = "NONE"
side = "CLIENT"
mandatory = true