modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "holographic_health_indicators"
version = "1.0.0"
displayName = "Holographic Health Indicators"
authors = "ray"
description = '''
Add client-sided, highly customizable, health indicators for entities.
'''
logoFile = "assets/holographic_health_indicators/icon.png"

[[dependencies.holographic_health_indicators]]
modId = "neoforge"
mandatory = true
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.holographic_health_indicators]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.holographic_health_indicators]]
modId = "cloth_config"
mandatory = true
versionRange = "[11.1.118,)"
ordering = "NONE"
side = "CLIENT"
[[dependencies.holographic_health_indicators]]
modId = "hologram_api"
mandatory = true
versionRange = "[1.1.0,)"
ordering = "NONE"
side = "CLIENT"

[[mixins]]
config = "better_damage_indicator.mixins.json"
